#if !defined(__GERAZERKIT_GERAZERSTANDARDBEHAVIOR__)
#define __GERAZERKIT_GERAZERSTANDARDBEHAVIOR__ 1

#include <CoreFoundation/CoreFoundation.h>

#endif /* ! __GERAZERKIT_GERAZERSTANDARDBEHAVIOR__ */
